GRMApp.Web/Areas/Customer/Controllers/HomeController.cs
using GRMApp.DataAccess.Data;
using GRMApp.DataAccess.IRepository;
using GRMApp.Models;
using GRMApp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GRMApp.Web.Areas.Customer.Controllers
{
    public class HomeController : Controller
    {
        private readonly IItemRepository _itemRepository;

        public HomeController(IItemRepository itemRepository)
        {
            _itemRepository = itemRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<Item> items = _itemRepository.GetAll();
            return View(items);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item item)
        {
            if (ModelState.IsValid)
            {
                item.Score = 0;
                _itemRepository.Add(item);
                return RedirectToAction("Index");
            }
            return View(item);
        }
    }
}

GRMApp.Web/Areas/Customer/Controllers/ItemDetailsController.cs
using GRMApp.DataAccess.IRepository;
using GRMApp.Models;
using GRMApp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;

namespace GRMApp.Web.Areas.Customer.Controllers
{
    public class ItemDetailsController : Controller
    {
        private readonly IItemDetailsRepository _itemDetailsRepository;
        private readonly IItemRepository _itemRepository;

        public ItemDetailsController(IItemDetailsRepository itemDetailsRepository, IItemRepository itemRepository)
        {
            _itemDetailsRepository = itemDetailsRepository;
            _itemRepository = itemRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            ItemsDetailsVM itemDetails = new()
            {
                ItemList = _itemRepository.GetAll().Select(i =>

                    new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    })
            };
            return View(itemDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ItemsDetailsVM model)
        {
            if (!ModelState.IsValid)
            {
                if (model.Score1 < model.Score2)
                {
                    _itemRepository.Update(model.ItemDetails2.ItemId);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    _itemRepository.Update(model.ItemDetails1.ItemId);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }
    }
}

GRMApp.Web/Areas/Customer/Views/Home/Create.cshtml
@model GRMApp.Models.Item

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Items</h2>
			<hr />
		</div>
		<div class="row g-3">
			<div class="col-4">
					<label asp-for="Name"></label>
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="col-12">
				<button type="submit" class="btn btn-primary" style="width:30%">Create</button>
				<a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:30%">
					Back to List
				</a>
			</div>
		</div>
			
	</div>
</form>

GRMApp.Web/Areas/Customer/Views/Home/Index.cshtml
@model IEnumerable<GRMApp.Models.Item>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Item List</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-area="Customer" asp-controller="Home" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Item
			</a>
		</div>
	</div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Position
			</th>
            <th>
                Name
			</th>
                <th>
                    Score
                </th>
		</tr>
	</thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="35%">
                    @obj.Position
				</td>
                <td width="30%">
                    @obj.Name
				</td>
                    <td width="35%">
                        @obj.Score
                    </td>
			</tr>
        }
    </tbody>

</table>
    <div class="col-12">
        <a asp-controller="ItemDetails" asp-action="Create" class="btn btn-secondary" style="width:30%">
            Item Detais
        </a>
    </div>
</div>

GRMApp.Web/Areas/Customer/Views/ItemDetails/Create.cshtml
@model GRMApp.Models.ViewModels.ItemsDetailsVM

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Details</h2>
			<hr />
		</div>
		<div class="row g-3">
			<div class="col-4">
				<label asp-for="ItemDetails1.ItemId">Item List</label>
				<select asp-for="ItemDetails1.ItemId" asp-items="@Model.ItemList" class="form-select">
					<option disabled selected>--Select Item--</option>
				</select>
				<span asp-validation-for="ItemDetails1.ItemId" class="text-danger"></span>
			</div>
			<div class="col-2">
				<label asp-for="Score1">Score</label>
				<input asp-for="Score1" class="form-control" />
				<span asp-validation-for="Score1" class="text-danger"></span>
			</div>
			<div class="col-2">
				<label asp-for="Score2">Score</label>
				<input asp-for="Score2" class="form-control" />
				<span asp-validation-for="Score2" class="text-danger"></span>
			</div>
				<div class="col-4">
				<label asp-for="ItemDetails2.ItemId">Item List</label>
				<select asp-for="ItemDetails2.ItemId" asp-items="@Model.ItemList" class="form-select">
					<option disabled selected>--Select Item--</option>
				</select>
				<span asp-validation-for="ItemDetails2.ItemId" class="text-danger"></span>
			</div>

			<div class="col-12">
				<button type="submit" class="btn btn-primary" style="width:30%">Create</button>
				<a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:30%">
					Back to List
				</a>
			</div>
		</div>

	</div>
</form>

GRMApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GRMApp.Web</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GRMApp.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GRM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GRMApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GRMApp.Web/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}